Fixed indentation of the SuSE part of the script from my previous commit.
svn-path: trunk@2304

diff --git a/sm5/smartd.initd.in b/sm5/smartd.initd.in
--- a/sm5/smartd.initd.in
+++ b/sm5/smartd.initd.in
@@ -2,7 +2,7 @@
 
 # smartmontools init file for smartd
 # Copyright (C) 2002-6 Bruce Allen <smartmontools-support@lists.sourceforge.net>
-# $Id: smartd.initd.in,v 1.34 2006/10/09 15:13:21 sbrabec Exp $
+# $Id: smartd.initd.in,v 1.35 2006/10/24 13:29:24 sbrabec Exp $
 
 # For RedHat and cousins:
 # chkconfig: 2345 40 40
@@ -190,21 +190,21 @@ elif [ -f /etc/SuSE-release ] ; then
             rc_status -v
 	    ;;
     try-restart|condrestart)
-	## Do a restart only if the service was active before.
-	## Note: try-restart is now part of LSB (as of 1.9).
-	## RH has a similar command named condrestart.
-	if test "$1" = "condrestart"; then
-		echo "${attn} Use try-restart ${done}(LSB)${attn} rather than condrestart ${warn}(RH)${norm}"
-	fi
-	$0 status
-	if test $? = 0; then
-		$0 restart 
-	else 
-		rc_reset	# Not running is not a failure.
-	fi
-	# Remember status and be quiet
-	rc_status
-	;;
+	    ## Do a restart only if the service was active before.
+	    ## Note: try-restart is now part of LSB (as of 1.9).
+	    ## RH has a similar command named condrestart.
+	    if test "$1" = "condrestart"; then
+		    echo "${attn} Use try-restart ${done}(LSB)${attn} rather than condrestart ${warn}(RH)${norm}"
+	    fi
+	    $0 status
+	    if test $? = 0; then
+		    $0 restart 
+	    else 
+		    rc_reset	# Not running is not a failure.
+	    fi
+	    # Remember status and be quiet
+	    rc_status
+	    ;;
     restart | force-reload)
 	    $0 stop
 	    $0 start
