Makefile.am: 'make check' now tests the syntax of drivedb.h.
git-svn-id: http://svn.code.sf.net/p/smartmontools/code/trunk@3005 4ea69e1a-61f1-4043-bf83-b5c94c648137

diff --git a/smartmontools/Makefile.am b/smartmontools/Makefile.am
--- a/smartmontools/Makefile.am
+++ b/smartmontools/Makefile.am
@@ -497,6 +497,14 @@ endif
 	$(MAN2TXT) $< > $@
 
 
+# Check drive database syntax
+check:
+	@if ./smartctl -B $(srcdir)/drivedb.h -P showall >/dev/null; then \
+	  echo "$(srcdir)/drivedb.h: OK"; \
+	else \
+	  echo "$(srcdir)/drivedb.h: Syntax check failed"; exit 1; \
+	fi
+
 
 if OS_WIN32_MINGW
 # Definitions for Windows distribution
