update-smart-drivedb.in: Allow update from local files or other URLs. Location could be specified with new options '--file' and '--url' (#1426). Check VERSION information to prevent downgrades. Allow override with new option '--force'. update-smart-drivedb.8.in: Document new functionality.
git-svn-id: http://svn.code.sf.net/p/smartmontools/code/trunk@5263 4ea69e1a-61f1-4043-bf83-b5c94c648137

diff --git a/smartmontools/update-smart-drivedb.in b/smartmontools/update-smart-drivedb.in
--- a/smartmontools/update-smart-drivedb.in
+++ b/smartmontools/update-smart-drivedb.in
@@ -64,12 +64,15 @@ Usage: $myname [OPTIONS] [DESTFILE]
                     svn (SVN repository) [default]
                     svni (SVN repository via HTTP instead of HTTPS)
                     trac (Trac code browser)
-  --trunk         Download from SVN trunk (may require '--no-verify')
+  --url URL       Download from URL
+  --file FILE     Copy from local FILE
+  --trunk         Download from SVN trunk (requires '--no-verify')
   --branch X.Y    Download from branches/RELEASE_X_Y_DRIVEDB
   --cacert FILE   Use CA certificates from FILE to verify the peer
   --capath DIR    Use CA certificate files from DIR to verify the peer
   --insecure      Don't abort download if certificate verification fails
   --no-verify     Don't verify signature
+  --force         Allow downgrades
   --export-key    Print the OpenPGP/GPG public key block
   --dryrun        Print download commands only
   -q              Suppress info messages
@@ -101,6 +104,7 @@ warning()
   echo "$myname: (Warning) $*" >&2
 }
 
+# selecturl URL_OF
 selecturl()
 {
   case $1 in
@@ -242,7 +246,6 @@ download()
 check_file()
 {
   local firstchar f maxsize minsize size
-  test -z "$dryrun" || return 0
   f=$1; firstchar=$2; minsize=$3; maxsize=$4
 
   # Check first chars
@@ -516,18 +519,40 @@ gpg_verify()
   return $rc
 }
 
+# get_db_version DRIVEDB > VERSION
+get_db_version()
+{
+  local r v x
+  x=$(sed -n '/^[ {]*"VERSION: *[^"]*"/{s,^[ {]*"VERSION: \([1-9][./0-9]* [^"]*\)".*$,\1,p;q}' "$1") \
+  || return 1
+  v=${x%% *}
+  test -n "$v" || return 0
+  if [ "${v%/*}" = "$v" ]; then # trunk: get rev from expanded SVN-Id
+    r=$(echo "$x" | sed -n 's,^[^$]*$Id: drivedb\.h \([1-9][0-9]*\) .*$,\1,p')
+    test -n "$r" || r="?"
+    v="$v/$r"
+  fi
+  echo "$v"
+}
+
 # mv_all PREFIX OLD NEW
 mv_all()
 {
-  mv "${1}${2}"         "${1}${3}"
-  mv "${1}${2}.raw"     "${1}${3}.raw"
-  mv "${1}${2}.raw.asc" "${1}${3}.raw.asc"
+  mv -f "${1}${2}" "${1}${3}" && \
+  mv -f "${1}${2}.raw" "${1}${3}.raw" && \
+  if [ -f "${1}${2}.raw.asc" ]; then
+    mv -f "${1}${2}.raw.asc" "${1}${3}.raw.asc"
+  else
+    rm -f "${1}${3}.raw.asc"
+  fi
 }
 
 # Parse options
 smartctl=$default_smartctl
 tool=
-urlid="svn"
+url_of=
+url=
+file=
 quiet=
 q="-q"
 dryrun=
@@ -537,6 +562,7 @@ cacert=
 capath=
 insecure=
 no_verify=
+force=
 expkey=
 
 while true; do case $1 in
@@ -552,7 +578,7 @@ while true; do case $1 in
 
   -u)
     shift; test -n "$1" || usage
-    urlid=$1 ;;
+    url_of=$1 ;;
 
   -q)
     quiet=t ;;
@@ -560,11 +586,19 @@ while true; do case $1 in
   -v)
     q= ;;
 
+  --url)
+    shift; test -n "$1" || usage
+    url=$1 ;;
+
+  --file)
+    shift; test -n "$1" || usage
+    file=$1 ;;
+
   --dryrun)
     dryrun=t ;;
 
   --trunk)
-    trunk=trunk ;;
+    trunk=t ;;
 
   --branch)
     shift
@@ -584,6 +618,9 @@ while true; do case $1 in
 
   --no-verify)
     no_verify=t ;;
+
+  --force)
+    force=t ;;
 
   --export-key)
     expkey=t ;;
@@ -610,9 +647,34 @@ case $# in
   *) usage ;;
 esac
 
-selecturl "$urlid"
+# Check selected source
+case "${url_of:+url_of}${url:+url}${file:+file}" in
+  ''|url_of)
+    test -n "$url_of" || url_of=svn
+    selecturl "$url_of"
+    if [ -z "$trunk" ]; then # select branch
+      url=`echo "$url" | sed -e "s,/trunk/,/branches/$branch/," \
+                             -e "s,/master/,/origin/$branch/,"`
+    elif [ -z "$no_verify" ]; then
+      error "'--trunk' requires '--no-verify'"
+    fi ;;
+  url)
+    test -z "`echo "$url" | sed -e 's,^[a-z][a-z0-9]*:[^ ][^ ]*$,,'`" \
+    || error "$url: Invalid URL" ;;
+  file) ;;
+  *) error "only one of '-u', '--url', '--file' is allowed" ;;
+esac
 
-if [ -z "$tool" ]; then
+# Determine path of signature file
+file_asc=
+url_asc=
+if [ -z "$no_verify" ]; then case $url in
+  '')   file_asc="$file.raw.asc" ;;
+  *\?*) url_asc=`echo "$url" | sed 's,?,.raw.asc?,'` ;;
+  *)    url_asc="$url.raw.asc" ;;
+esac; fi
+
+if [ -z "$tool$file" ]; then
   # Find download tool in PATH
   for t in $os_dltools; do
     if inpath "$t"; then
@@ -624,17 +686,16 @@ if [ -z "$tool" ]; then
 fi
 
 # Check option compatibility
-case "$tool:$url" in
-  svn:http*://svn.code.sf.net*) ;;
+case "$tool:$url_of" in
+  svn:svn*) ;;
   svn:*) error "'-t svn' requires '-u svn' or '-u svni'" ;;
 esac
 case "$tool:${capath:+set}" in
   svn:set) warning "'--capath' is ignored if '-t svn' is used" ;;
 esac
-case "${insecure:-f}:$url" in
-  t:http:*) insecure= ;;
-  ?:https:*) ;;
-  *) error "'-u svni' requires '--insecure'" ;;
+case "$url_of:$insecure" in
+  svni:t) insecure= ;;
+  svni:*) error "'-u svni' requires '--insecure'" ;;
 esac
 case "$tool:$insecure" in
   lynx:t) warning "'--insecure' is ignored if '-t lynx' is used" ;;
@@ -664,56 +725,113 @@ fi
 # Use destination directory as temp directory for gpg
 tmpdir=`dirname "$drivedb"`
 
-# Adjust URLs
-src=`echo "$url" | sed -e "s,/trunk/,/branches/$branch/," \
-                       -e "s,/master/,/origin/$branch/,"`
-src_asc=`echo "$src" | sed "s,/drivedb\.h,/drivedb.h.raw.asc,"`
-test -z "$trunk" || src=$url
+# Remove possible garbage from last download
+test -n "$dryrun" || rm -f "$drivedb.new" "$drivedb.new.raw" "$drivedb.new.raw.asc" || exit 1
 
-# Download
-test -n "$dryrun" || rm -f "$drivedb.new" "$drivedb.new.raw" "$drivedb.new.raw.asc"
+if [ -n "$url" ]; then
+  # Download
+  vecho "Download drivedb.h with $tool"
+  rc=0
+  download "$url" "$drivedb.new" || rc=$?
+  if [ $rc != 0 ]; then
+    rm -f "$drivedb.new"
+    error "drivedb.h: download failed ($tool: exit $rc)"
+  fi
 
-vecho "Download ${trunk:-branches/$branch}/drivedb.h with $tool"
-rc=0
-download "$src" "$drivedb.new" || rc=$?
-if [ $rc != 0 ]; then
-  rm -f "$drivedb.new"
-  error "${trunk:-$branch}/drivedb.h: download failed ($tool: exit $rc)"
-fi
-if ! errmsg=`check_file "$drivedb.new" '/' 10000 1000000`; then
-  mv "$drivedb.new" "$drivedb.error"
-  error "$drivedb.error: $errmsg"
-fi
+  if [ -n "$url_asc" ]; then
+    vecho "Download drivedb.h.raw.asc with $tool"
+    rc=0
+    download "$url_asc" "$drivedb.new.raw.asc" || rc=$?
+    if [ $rc != 0 ]; then
+      rm -f "$drivedb.new" "$drivedb.new.raw.asc"
+      error "drivedb.h.raw.asc: download failed ($tool: exit $rc) ('--no-verify' to ignore)"
+    fi
+  fi
+else
+  # Copy from local file
+  if [ ! -f "$file" ]; then
+    error "$file: file not found"
+  fi
+  if [ -n "$file_asc" ] && [ ! -f "$file_asc" ]; then
+    error "$file_asc: file not found ('--no-verify' to ignore)"
+  fi
 
-vecho "Download branches/$branch/drivedb.h.raw.asc with $tool"
-rc=0
-download "$src_asc" "$drivedb.new.raw.asc" || rc=$?
-if [ $rc != 0 ]; then
-  rm -f "$drivedb.new" "$drivedb.new.raw.asc"
-  error "$branch/drivedb.h.raw.asc: download failed ($tool: exit $rc)"
-fi
-if ! errmsg=`check_file "$drivedb.new.raw.asc" '-' 200 2000`; then
-  rm -f "$drivedb.new"
-  mv "$drivedb.new.raw.asc" "$drivedb.error.raw.asc"
-  error "$drivedb.error.raw.asc: $errmsg"
+  if ! vrun cp "$file" "$drivedb.new"; then
+    error "$file: copy failed"
+  fi
+  if [ -n "$file_asc" ]; then
+    if ! vrun cp "$file_asc" "$drivedb.new.raw.asc"; then
+      rm -f "$drivedb.new"
+      error "$file_asc: copy failed"
+    fi
+  fi
 fi
 
 test -z "$dryrun" || exit 0
 
+# Check files, adjust timestamps and permissions
+if ! errmsg=`check_file "$drivedb.new" '/' 10000 1000000`; then
+  rm -f "$drivedb.new.raw.asc"
+  mv -f "$drivedb.new" "$drivedb.error"
+  error "$drivedb.error: $errmsg"
+fi
+touch "$drivedb.new"
+chmod 0644 "$drivedb.new"
+
+if [ -f "$drivedb.new.raw.asc" ]; then
+  if ! errmsg=`check_file "$drivedb.new.raw.asc" '-' 200 2000`; then
+    rm -f "$drivedb.new"
+    mv -f "$drivedb.new.raw.asc" "$drivedb.error.raw.asc"
+    error "$drivedb.error.raw.asc: $errmsg"
+  fi
+  touch "$drivedb.new.raw.asc"
+  chmod 0644 "$drivedb.new.raw.asc"
+fi
+
 # Create raw file with unexpanded SVN Id
 # (This assumes newlines are LF and not CR/LF)
 unexpand_svn_id < "$drivedb.new" > "$drivedb.new.raw"
+chmod 0644 "$drivedb.new.raw"
 
-# Adjust timestamps and permissions
-touch "$drivedb.new" "$drivedb.new.raw" "$drivedb.new.raw.asc"
-chmod 0644 "$drivedb.new" "$drivedb.new.raw" "$drivedb.new.raw.asc"
+# Check whether installed file is identical
+equal=
+if [ -f "$drivedb" ]; then
+  if [ ! -f "$drivedb.raw" ]; then
+    # Create missing raw file
+    unexpand_svn_id < "$drivedb" > "$drivedb.raw"
+    chmod 0644 "$drivedb.raw"
+  fi
+  # Ignore missing Id keyword expansion in new file
+  if    cmp "$drivedb.raw" "$drivedb.new.raw" >/dev/null 2>&1 \
+     && {   cmp "$drivedb"     "$drivedb.new" >/dev/null 2>&1 \
+         || cmp "$drivedb.raw" "$drivedb.new" >/dev/null 2>&1; }
+  then
+    equal=t
+  fi
+fi
 
 if [ -z "$no_verify" ]; then
   # Verify raw file
   if ! gpg_verify "$drivedb.new.raw.asc" "$drivedb.new.raw"; then
     mv_all "$drivedb" ".new" ".error"
-    test -n "$trunk" || error "$drivedb.error.raw: *** BAD signature or outdated key ***"
-    error "$drivedb.error.raw: signature from branch no longer valid ('--no-verify' to ignore)"
+    test -z "$equal" \
+    || warning "$drivedb: *** installed file is identical to broken new file ***"
+    error "$drivedb.error.raw: *** BAD signature or outdated key ***"
+  fi
+fi
+
+# Get version
+newver=$(get_db_version "$drivedb.new")
+if [ -z "$newver" ]; then
+  if [ -z "$force" ]; then
+    mv_all "$drivedb" ".new" ".error"
+    error "$drivedb.error: no VERSION information found ('--force' to ignore)"
+  fi
+  newver="?/?"
+elif [ "${newver##*/}" = "?" ]; then
+  if [ -z "$trunk" ]; then
+    mv_all "$drivedb" ".new" ".error"
+    error "$drivedb.error: VERSION information is incomplete ('--trunk' to ignore)"
   fi
 fi
 
@@ -726,26 +844,47 @@ if [ "$smartctl" != "-" ]; then
   vecho "$smartctl: syntax OK"
 fi
 
-# Keep old file if identical, ignore missing Id keyword expansion in new file
+# Always install if missing
 rm -f "$drivedb.lastcheck"
-if [ -f "$drivedb" ]; then
-  if [ -f "$drivedb.raw" ] && [ -f "$drivedb.raw.asc" ]; then
-    if    cmp "$drivedb.raw"     "$drivedb.new.raw"     >/dev/null 2>&1 \
-       && cmp "$drivedb.raw.asc" "$drivedb.new.raw.asc" >/dev/null 2>&1 \
-       && {   cmp "$drivedb"     "$drivedb.new" >/dev/null 2>&1 \
-           || cmp "$drivedb.raw" "$drivedb.new" >/dev/null 2>&1; }
-    then
-      rm -f "$drivedb.new" "$drivedb.new.raw" "$drivedb.new.raw.asc"
-      touch "$drivedb.lastcheck"
-      iecho "$drivedb is already up to date"
-      exit 0
-    fi
-    mv_all "$drivedb" "" ".old"
-  else
-    mv "$drivedb" "$drivedb.old"
-  fi
+if [ ! -f "$drivedb" ]; then
+  mv_all "$drivedb" ".new" ""
+  iecho "$drivedb $newver newly installed${no_verify:+ (NOT VERIFIED)}"
+  exit 0
 fi
 
-mv_all "$drivedb" ".new" ""
+# Keep old file if identical
+if [ -n "$equal" ]; then
+  if    [ -f "$drivedb.new.raw.asc" ] \
+     && ! cmp "$drivedb.new.raw.asc" "$drivedb.raw.asc" >/dev/null 2>&1; then
+    mv -f "$drivedb.new.raw.asc" "$drivedb.raw.asc"
+    iecho "$drivedb.raw.asc $newver updated"
+  fi
+  rm -f "$drivedb.new" "$drivedb.new.raw" "$drivedb.new.raw.asc"
+  touch "$drivedb.lastcheck"
+  iecho "$drivedb $newver is already up to date${no_verify:+ (NOT VERIFIED)}"
+  exit 0
+fi
 
-iecho "$drivedb updated from ${trunk:-branches/$branch}${no_verify:+ (NOT VERIFIED)}"
+# Check branch and file version
+oldver=$(get_db_version "$drivedb")
+test -n "$oldver" || oldver="?/?"
+if    [ "${newver##*/}" = "?" ] \
+   || [ "${oldver##*/}" = "?" ] \
+   || [ "${newver%/*}" != "${oldver%/*}" ]; then
+  # Always install from trunk or other branch
+  updmsg="replaced with"
+elif [ "${newver##*/}" -lt "${oldver##*/}" ]; then
+  # Install older file only if '--force' is used
+  if [ -z "$force" ]; then
+    rm -f "$drivedb.new" "$drivedb.new.raw" "$drivedb.new.raw.asc"
+    iecho "$drivedb $oldver not downgraded to $newver ('--force' to override)"
+    exit 0
+  fi
+  updmsg="downgraded to"
+else
+  updmsg="updated to"
+fi
+
+mv_all "$drivedb" "" ".old"
+mv_all "$drivedb" ".new" ""
+iecho "$drivedb $oldver $updmsg $newver${no_verify:+ (NOT VERIFIED)}"
