Library: move the examples from 'lib/examples' to 'src/examples'
Signed-off-by: Christian Franke <christian.franke@t-online.de>

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -357,16 +357,15 @@ $(smartd_service): smartd.service.in Makefile
 
 # Create empty directories if configured.
 # Default install rules no longer create empty directories since automake 1.11.
-installdirs-local:
+install-empty-dirs:
 	@for d in '$(smartdplugindir)' '$(drivedbdir)' '$(savestatesdir)' '$(attributelogdir)' '$(jsonstatedir)'; do \
 	  test -n "$$d" || continue; \
 	  echo " $(MKDIR_P) '$(DESTDIR)$$d'"; \
 	  $(MKDIR_P) "$(DESTDIR)$$d" || exit 1; \
 	done
 
-all-local: $(all_local)
-install-data-local: $(install_data_local) installdirs-local
-uninstall-local: $(uninstall_local)
+install-data-local: $(install_data_local) install-empty-dirs
+installdirs_local = install-empty-dirs
 
 #
 # Build man pages
@@ -549,9 +548,103 @@ smartd.conf.5.pdf: smartd.conf.5
 update-smart-drivedb.8.pdf: update-smart-drivedb.8
 	$(AM_V_GEN)$(MAN2PDF) update-smart-drivedb.8 > $@
 
-# Default check target
+# Library examples
+phony += clean-examples examples
+
+examples_cpp = \
+        examples/ata-standby.cpp \
+        examples/lsdisk.cpp
+
+EXTRA_DIST += \
+        examples/Makefile.in \
+        $(examples_cpp)
+
+examples: examples.stamp
+
+examples.stamp: ../lib/libsmartmon.la examples/Makefile examples/make.sh
+	$(AM_V_at)examples/make.sh V=$(V) clean
+	$(AM_V_at)examples/make.sh V=$(V)
+	$(AM_V_at)touch $@
+
+examples/Makefile: examples/Makefile.in ../Makefile
+	$(MAKE) -C .. src/examples/Makefile
+
+examples/make.sh: Makefile
+	$(ECHO_V_GEN) ' $$(CREATE_MAKE_SH) > $@.tmp'
+	@sbindir='$(develbindir)'; \
+	( \
+	  echo "#!$(SHELL)"; \
+	  echo "# src/examples/make.sh. Generated by src/Makefile."; \
+	  echo "set -e"; \
+	  echo 'd=$$(dirname "$$0")'; \
+	  echo 'case " $$* " in *\ V=0\ *) ;; *) set -x ;; esac'; \
+	  echo 'cd "$$d"'; \
+	  echo "exec $(MAKE) \\"; \
+	  echo "  VPATH='$(abs_top_srcdir)/src/examples' \\"; \
+	  echo "  CXX='$(CXX)' \\"; \
+	  echo "  CPPFLAGS='-I$(abs_top_builddir)/include -I$(abs_top_srcdir)/include $(examples_cppflags)' \\"; \
+	  echo "  LDFLAGS='-L$(abs_top_builddir)/lib/.libs $(examples_ldflags)' \\"; \
+	  echo "  SBINDIR=$${sbindir:-'$(abs_top_builddir)/src/examples/test-install'} \\"; \
+	  echo '  "$$@"' \
+	) > $@.tmp
+	$(AM_V_at)chmod +x $@.tmp
+	$(AM_V_at)mv -f $@.tmp $@
+
+clean-examples:
+	if [ -f examples/make.sh ]; then \
+	  examples/make.sh V=$(V) clean && rm -f examples/make.sh; \
+	fi
+	rm -f examples/make.sh.tmp examples.stamp
+
+clean-local: clean-examples
+
+if INSTALL_DEVEL_SRC
+# Install example source codes
+
+develsrc_DATA = \
+        examples/Makefile \
+        $(examples_cpp)
+
+endif
+
+check =
+
+if INSTALL_DEVEL_BIN
+# Install example binaries
+phony += installdir-examples install-examples uninstall-examples
+
+all_local += examples
+install-exec-local: install-examples
+uninstall_local += uninstall-examples
+
+installdirs_local += installdir-examples
+installdir-examples:
+	$(MKDIR_P) $(DESTDIR)$(develbindir)
+
+install-examples: examples
+	examples/make.sh V=$(V) DESTDIR=$(DESTDIR) install
+
+uninstall-examples:
+	if [ -f examples/make.sh ]; then \
+	  examples/make.sh V=$(V) DESTDIR=$(DESTDIR) uninstall; \
+	fi
+
+else
+
+# Build examples and report failure via a GHA annotation instead of nonzero exit status
+check += check-examples
+check-examples:
+	$(MAKE) examples || echo '::error:: Build of libsmartmon examples failed'
+
+endif
+
+all-local: $(all_local)
+installdirs-local: $(installdirs_local)
+uninstall-local: $(uninstall_local)
+
+# Checks
 phony += check-drivedb check-smartctl
-check: check-drivedb check-smartctl
+check += check-drivedb check-smartctl
 
 # Print updated drivedb.h "VERSION: ..." string
 check-drivedb:
@@ -572,6 +665,8 @@ check-smartctl:
 	  echo "$../lib/drivedb.h: Syntax check failed"; exit 1; \
 	fi
 endif
+
+check: $(check)
 
 # Create cppcheck report
 cppcheck: cppcheck.txt
