Drop creation of 'drivedb.h.raw' file during drive database updates
No longer needed because svn Id keywords could no longer be used to
detect the revision.  Download 'drivedb.h.raw.asc' as 'drivedb.h.asc'.

Signed-off-by: Christian Franke <christian.franke@t-online.de>

diff --git a/src/update-smart-drivedb.in b/src/update-smart-drivedb.in
--- a/src/update-smart-drivedb.in
+++ b/src/update-smart-drivedb.in
@@ -20,6 +20,7 @@ exec_prefix="@exec_prefix@"
 sbindir="@sbindir@"
 datarootdir="@datarootdir@"
 datadir="@datadir@"
+# shellcheck disable=SC2034
 localstatedir="@localstatedir@"
 drivedbinstdir="@drivedbinstdir@"
 drivedbdir="@drivedbdir@"
@@ -190,6 +191,17 @@ vrun2()
   return $rc
 }
 
+# rm_f FILE...
+rm_f()
+{
+  while [ $# -ne 0 ]; do
+    if [ -f "$1" ]; then
+      vrun rm -f "$1"
+    fi
+    shift
+  done
+}
+
 # download URL FILE
 download()
 {
@@ -270,12 +282,6 @@ check_file()
     return 1
   fi
   return 0
-}
-
-# unexpand_svn_id < INFILE > OUTFILE
-unexpand_svn_id()
-{
-  sed 's,\$''Id'': drivedb\.h [0-9][0-9]* 2[-0-9]* [012][:0-9]*Z [a-z][a-z0-9]* \$,$''Id''$,'
 }
 
 # selectkey BRANCH
@@ -438,16 +444,26 @@ get_db_version()
   echo "$v"
 }
 
-# mv_all PREFIX OLD NEW
-mv_all()
+# drivedb_mv OLD NEW
+drivedb_mv()
 {
-  mv -f "${1}${2}" "${1}${3}" && \
-  mv -f "${1}${2}.raw" "${1}${3}.raw" && \
-  if [ -f "${1}${2}.raw.asc" ]; then
-    mv -f "${1}${2}.raw.asc" "${1}${3}.raw.asc"
-  else
-    rm -f "${1}${3}.raw.asc"
-  fi
+  local ext nf of
+  for ext in "" ".asc" ".raw" ".raw.asc"; do
+    of="${drivedb}${1}${ext}"
+    nf="${drivedb}${2}${ext}"
+    if [ -f "$of" ]; then
+      vrun mv -f "$of" "$nf"
+    else
+      rm_f "$nf"
+    fi
+  done
+}
+
+# drivedb_error "MESSAGE"
+drivedb_error()
+{
+  drivedb_mv ".new" ".error"
+  error "${drivedb}.error${1}"
 }
 
 # Parse options
@@ -511,8 +527,10 @@ while true; do case $1 in
   --branch)
     check_optarg "$@"; shift
     branch=$1
-    test -z "`echo "$branch" | sed 's,^[5-7]\.[0-6]$,,'`" \
-    || error "invalid branch '$branch'" ;;
+    case $branch in
+      5.4[0-3]|6.[0-6]|7.[0235]) ;;
+      *) error "invalid branch '$branch'" ;;
+    esac ;;
 
   --cacert)
     check_optarg "$@"; shift
@@ -590,14 +608,24 @@ case "${url_of:+url_of}${url:+url}${file:+file}" in
 esac
 
 # Determine path of signature file
-# TODO: remove '.raw' for branches >= 8.0
 file_asc=
+file_raw_asc=
 url_asc=
-if [ -z "$no_verify" ]; then case $url in
-  '')   file_asc="$file.raw.asc" ;;
-  *\?*) url_asc=`echo "$url" | sed 's,?,.raw.asc?,'` ;;
-  *)    url_asc="$url.raw.asc" ;;
-esac; fi
+if [ -z "$no_verify" ]; then
+  if [ -n "$url" ]; then
+    case $branch in
+      [567].*) raw=".raw" ;;
+      *) raw= ;;
+    esac
+    case $url in
+      *\?*) url_asc=`echo "$url" | sed "s,?,$raw.asc?,"` ;;
+      *)    url_asc="$url$raw.asc" ;;
+    esac
+  else
+    file_asc="$file.asc"
+    file_raw_asc="$file.raw.asc"
+  fi
+fi
 
 if [ -z "$file" ]; then
   if [ -z "$tool" ]; then
@@ -652,7 +680,7 @@ usageerr=
 tmpdir=`dirname "$drivedb"`
 
 # Remove possible garbage from last download
-test -n "$dryrun" || rm -f "$drivedb.new" "$drivedb.new.raw" "$drivedb.new.raw.asc" || exit 1
+rm_f "$drivedb.new" "$drivedb.new.asc" "$drivedb.new.raw" "$drivedb.new.raw.asc" || exit 1
 
 if [ -n "$url" ]; then
   # Download
@@ -660,17 +688,17 @@ if [ -n "$url" ]; then
   rc=0
   download "$url" "$drivedb.new" || rc=$?
   if [ $rc != 0 ]; then
-    rm -f "$drivedb.new"
+    rm_f "$drivedb.new"
     error "drivedb.h: download failed ($tool: exit $rc)"
   fi
 
   if [ -n "$url_asc" ]; then
-    vecho "Download drivedb.h.raw.asc with $tool"
+    vecho "Download drivedb.h.asc with $tool"
     rc=0
-    download "$url_asc" "$drivedb.new.raw.asc" || rc=$?
+    download "$url_asc" "$drivedb.new.asc" || rc=$?
     if [ $rc != 0 ]; then
-      rm -f "$drivedb.new" "$drivedb.new.raw.asc"
-      error "drivedb.h.raw.asc: download failed ($tool: exit $rc) ('--no-verify' to ignore)"
+      rm_f "$drivedb.new" "$drivedb.new.asc"
+      error "drivedb.h.asc: download failed ($tool: exit $rc) ('--no-verify' to ignore)"
     fi
   fi
 else
@@ -678,16 +706,20 @@ else
   if [ ! -f "$file" ]; then
     error "$file: file not found"
   fi
-  if [ -n "$file_asc" ] && [ ! -f "$file_asc" ]; then
-    error "$file_asc: file not found ('--no-verify' to ignore)"
+  if [ -n "$file_asc" ]; then
+    if [ ! -f "$file_asc" ]; then
+      test -f "$file_raw_asc" \
+      || error "$file_asc, $file_raw_asc: file not found ('--no-verify' to ignore)"
+      file_asc=$file_raw_asc
+    fi
   fi
 
   if ! vrun cp "$file" "$drivedb.new"; then
     error "$file: copy failed"
   fi
   if [ -n "$file_asc" ]; then
-    if ! vrun cp "$file_asc" "$drivedb.new.raw.asc"; then
-      rm -f "$drivedb.new"
+    if ! vrun cp "$file_asc" "$drivedb.new.asc"; then
+      rm_f "$drivedb.new"
       error "$file_asc: copy failed"
     fi
   fi
@@ -696,96 +728,65 @@ fi
 test -z "$dryrun" || exit 0
 
 # Check files, adjust timestamps and permissions
-if ! errmsg=`check_file "$drivedb.new" '/' 10000 1000000`; then
-  rm -f "$drivedb.new.raw.asc"
-  mv -f "$drivedb.new" "$drivedb.error"
-  error "$drivedb.error: $errmsg"
-fi
+errmsg=`check_file "$drivedb.new" '/' 10000 1000000` \
+|| drivedb_error ": $errmsg"
 touch "$drivedb.new"
 chmod 0644 "$drivedb.new"
 
-if [ -f "$drivedb.new.raw.asc" ]; then
-  if ! errmsg=`check_file "$drivedb.new.raw.asc" '-' 200 2000`; then
-    rm -f "$drivedb.new"
-    mv -f "$drivedb.new.raw.asc" "$drivedb.error.raw.asc"
-    error "$drivedb.error.raw.asc: $errmsg"
-  fi
-  touch "$drivedb.new.raw.asc"
-  chmod 0644 "$drivedb.new.raw.asc"
+if [ -f "$drivedb.new.asc" ]; then
+  errmsg=`check_file "$drivedb.new.asc" '-' 200 2000` \
+  || drivedb_error ".asc: $errmsg"
+  touch "$drivedb.new.asc"
+  chmod 0644 "$drivedb.new.asc"
 fi
-
-# Create raw file with unexpanded SVN Id
-# (This assumes newlines are LF and not CR/LF)
-unexpand_svn_id < "$drivedb.new" > "$drivedb.new.raw"
-chmod 0644 "$drivedb.new.raw"
 
 # Check whether installed file is identical
-equal=
-if [ -f "$drivedb" ]; then
-  if [ ! -f "$drivedb.raw" ]; then
-    # Create missing raw file
-    unexpand_svn_id < "$drivedb" > "$drivedb.raw"
-    chmod 0644 "$drivedb.raw"
-  fi
-  # Ignore missing Id keyword expansion in new file
-  if    cmp "$drivedb.raw" "$drivedb.new.raw" >/dev/null 2>&1 \
-     && {   cmp "$drivedb"     "$drivedb.new" >/dev/null 2>&1 \
-         || cmp "$drivedb.raw" "$drivedb.new" >/dev/null 2>&1; }
-  then
-    equal=t
-  fi
-fi
+equal=t
+cmp "$drivedb" "$drivedb.new" >/dev/null 2>&1 || equal=
 
 if [ -z "$no_verify" ]; then
-  # Verify raw file
-  if ! gpg_verify "$drivedb.new.raw.asc" "$drivedb.new.raw"; then
-    mv_all "$drivedb" ".new" ".error"
+  # Verify new file
+  if ! gpg_verify "$drivedb.new.asc" "$drivedb.new"; then
     test -z "$equal" \
     || warning "$drivedb: *** installed file is identical to broken new file ***"
-    error "$drivedb.error.raw: *** BAD signature or outdated key ***"
+    drivedb_error ": *** BAD signature or outdated key ***"
   fi
 fi
 
 # Get version
 newver=`get_db_version "$drivedb.new"`
 if [ -z "$newver" ]; then
-  if [ -z "$force" ]; then
-    mv_all "$drivedb" ".new" ".error"
-    error "$drivedb.error: no VERSION information found ('--force' to ignore)"
-  fi
+  test -n "$force" \
+  || drivedb_error ": no VERSION information found ('--force' to ignore)"
   newver="?/?"
 elif [ "${newver##*/}" = "?" ]; then
-  if [ -z "$main" ]; then
-    mv_all "$drivedb" ".new" ".error"
-    error "$drivedb.error: VERSION information is incomplete ('--main' to ignore)"
-  fi
+  test -n "$main" \
+  || drivedb_error ": VERSION information is incomplete ('--main' to ignore)"
 fi
 
 if [ "$smartctl" != "-" ]; then
   # Check syntax
-  if ! "$smartctl" -B "$drivedb.new" -P showall >/dev/null; then
-    mv_all "$drivedb" ".new" ".error"
-    error "$drivedb.error: rejected by $smartctl, probably no longer compatible"
-  fi
+  "$smartctl" -B "$drivedb.new" -P showall >/dev/null \
+  || drivedb_error ": rejected by $smartctl, probably no longer compatible"
   vecho "$smartctl: syntax OK"
 fi
 
 # Always install if missing
 rm -f "$drivedb.lastcheck"
 if [ ! -f "$drivedb" ]; then
-  mv_all "$drivedb" ".new" ""
+  drivedb_mv ".new" ""
   iecho "$drivedb $newver newly installed${no_verify:+ (NOT VERIFIED)}"
   exit 0
 fi
 
 # Keep old file if identical
 if [ -n "$equal" ]; then
-  if    [ -f "$drivedb.new.raw.asc" ] \
-     && ! cmp "$drivedb.new.raw.asc" "$drivedb.raw.asc" >/dev/null 2>&1; then
-    mv -f "$drivedb.new.raw.asc" "$drivedb.raw.asc"
-    iecho "$drivedb.raw.asc $newver updated"
+  if    [ -f "$drivedb.new.asc" ] \
+     && ! cmp "$drivedb.new.asc" "$drivedb.asc" >/dev/null 2>&1; then
+    vrun mv -f "$drivedb.new.asc" "$drivedb.asc"
+    iecho "$drivedb.asc $newver updated"
   fi
-  rm -f "$drivedb.new" "$drivedb.new.raw" "$drivedb.new.raw.asc"
+  rm_f "$drivedb.new" "$drivedb.new.asc" "$drivedb.raw" "$drivedb.raw.asc"
   touch "$drivedb.lastcheck"
   iecho "$drivedb $newver is already up to date${no_verify:+ (NOT VERIFIED)}"
   exit 0
@@ -802,7 +803,7 @@ if    [ "${newver##*/}" = "?" ] \
 elif [ "${newver##*/}" -lt "${oldver##*/}" ]; then
   # Install older file only if '--force' is used
   if [ -z "$force" ]; then
-    rm -f "$drivedb.new" "$drivedb.new.raw" "$drivedb.new.raw.asc"
+    rm_f "$drivedb.new" "$drivedb.new.asc"
     iecho "$drivedb $oldver not downgraded to $newver ('--force' to override)"
     exit 0
   fi
@@ -811,6 +812,6 @@ else
   updmsg="updated to"
 fi
 
-mv_all "$drivedb" "" ".old"
-mv_all "$drivedb" ".new" ""
+drivedb_mv "" ".old"
+drivedb_mv ".new" ""
 iecho "$drivedb $oldver $updmsg $newver${no_verify:+ (NOT VERIFIED)}"
