Workflows: qemu: add NetBSD Sparc64 (Big Endian)
Signed-off-by: Christian Franke <christian.franke@t-online.de>

diff --git a/.github/workflows/qemu.yml b/.github/workflows/qemu.yml
--- a/.github/workflows/qemu.yml
+++ b/.github/workflows/qemu.yml
@@ -1,4 +1,4 @@
-name: Build on various platforms (QEMU)
+name: Build smartmontools on QEMU
 
 on:
   workflow_dispatch:
@@ -7,7 +7,8 @@ on:
         description: Build platforms (defaults to all)
         required: false
         default: >-
-          freebsd-x86_64 freebsd-arm64 freebsd-powerpc64 netbsd openbsd openindiana
+          freebsd-x86_64 freebsd-arm64 freebsd-powerpc64
+          netbsd-x86_64 netbsd-sparc64 openbsd openindiana
 
 jobs:
   build-source-tarball:
@@ -144,7 +145,7 @@ jobs:
           retention-days: 90
 
   build-netbsd-x86_64:
-    if: ${{ contains(github.event.inputs.platforms, 'netbsd') }}
+    if: ${{ contains(github.event.inputs.platforms, 'netbsd-x86_64') }}
     needs: build-source-tarball
     runs-on: ubuntu-latest
     steps:
@@ -174,6 +175,42 @@ jobs:
       - uses: actions/upload-artifact@v7
         with:
           name: smartmontools-netbsd-x86_64
+          path: smartmontools-netbsd-*.tar.gz
+          retention-days: 90
+
+  build-netbsd-sparc64: # Big Endian
+    if: ${{ contains(github.event.inputs.platforms, 'netbsd-sparc64') }}
+    needs: build-source-tarball
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/download-artifact@v8
+        with:
+          name: smartmontools-src
+
+      - name: Build (QEMU)
+        uses: vmactions/netbsd-vm@v1
+        with:
+          arch: sparc64
+          sync: scp # 'rsync' not supported in release 11.0
+          usesh: true
+          run: | # SOURCE_DATE_EPOCH not used because GNU tar is not installed by default
+            uname -a && ver=$(uname -r) && ver=${ver%%.*} &&
+            distfile=$(ls -d smartmontools-*.tar.gz) &&
+            test "$(echo "$distfile" | wc -l | tr -d ' ')" = 1 &&
+            tar -xf "$distfile" && distdir=${distfile%-*-g*.tar.gz} &&
+            version_sh=$("$distdir/src/getversion.sh" -s) && eval "${version_sh}" &&
+            cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
+            ../configure --with-build-info='(GHA/qemu)' &&
+            make -j4 && make check &&
+            bin_distfile="../../smartmontools-netbsd-$ver-sparc64-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" &&
+            make bin_distfile="$bin_distfile" bin-dist && tar -tvf "$bin_distfile" &&
+            tar -xf "$bin_distfile" usr/local/sbin/smartctl &&
+            echo '$' usr/local/sbin/smartctl --scan &&
+            { usr/local/sbin/smartctl --scan || echo "::error::'smartctl --scan' failed"; }
+
+      - uses: actions/upload-artifact@v7
+        with:
+          name: smartmontools-netbsd-sparc64
           path: smartmontools-netbsd-*.tar.gz
           retention-days: 90
 
